// Run with Playwright available on NODE_PATH and the site served on port 8765.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = []; page.on('pageerror', err => errors.push(err.message));
  await page.goto('http://127.0.0.1:8765/00-assets/html/player-database.htm');
  await page.locator('#resultSummary').filter({ hasText: /\d+ of \d+ players/ }).waitFor();
  const summary = await page.locator('#resultSummary').textContent();
  assert.equal(await page.locator('th [data-sort="height"]').count(), 1);
  await page.locator('#tab-potential').click();
  await page.waitForFunction(() => new URLSearchParams(location.search).get('tab') === 'potential');
  assert.equal(await page.locator('th [data-sort="height"]').count(), 1);
  await page.locator('#dbOpenFilters').click();
  await page.locator('[data-add="conditions"]').click();
  await page.locator('[data-section="conditions"] [data-rule-part="field"]').selectOption('height');
  await page.locator('[data-section="conditions"] [data-rule-part="value"]').selectOption('84');
  await page.locator('[data-apply]').click();
  assert.match(await page.locator('.db-filter-chips').textContent(), /Height ≥ 7′0″/);
  assert.ok(await page.locator('tbody tr').count() > 0);
  const heights = await page.locator('tbody tr').evaluateAll(rows => rows.map(r => r.cells[3].textContent));
  assert.ok(heights.every(h => Number(h.split('′')[0]) >= 7));
  await page.locator('#resetFilters').click();
  await page.locator('#tab-attributes').click();
  await page.waitForFunction(() => new URLSearchParams(location.search).get('tab') === 'attributes');
  for (const id of ['positionFilter', 'teamFilter', 'statusFilter']) { assert.equal(await page.locator('#' + id).isVisible(), true); }
  const filterBounds = await page.locator('#dbOpenFilters').boundingBox(), tabBounds = await page.locator('#tab-attributes').boundingBox();
  assert.ok(Math.abs(filterBounds.y - tabBounds.y) < 15);
  await page.locator('#positionFilter').selectOption('SG');
  await page.locator('#dbOpenFilters').click();
  assert.equal(await page.locator('[data-position="SG"]').getAttribute('aria-pressed'), 'true');
  await page.locator('[data-position="SF"]').click();
  await page.locator('[data-apply]').click();
  assert.equal(await page.locator('#positionFilter').inputValue(), 'multiple');
  await page.locator('#statusFilter').selectOption('rostered');
  await page.locator('#dbOpenFilters').click();
  assert.equal(await page.locator('[data-basic="status"]').inputValue(), 'rostered');
  assert.equal(await page.locator('[data-position="SF"]').getAttribute('aria-pressed'), 'true');
  await page.locator('[data-clear]').click();
  await page.locator('[data-apply]').click();
  const teamHeader = await page.locator('[data-sort="team"]').boundingBox();
  const ageHeader = await page.locator('[data-sort="age"]').boundingBox();
  await page.mouse.move(teamHeader.x + teamHeader.width / 2, teamHeader.y + teamHeader.height / 2);
  await page.mouse.down();
  await page.mouse.move(ageHeader.x + ageHeader.width - 1, ageHeader.y + ageHeader.height / 2, { steps: 12 });
  await page.mouse.up();
  assert.deepEqual(await page.locator('th [data-sort]').evaluateAll(els => els.slice(0, 4).map(el => el.dataset.sort)), ['name', 'pos', 'age', 'team']);
  assert.equal(await page.locator('[data-sort="overall"]').evaluate(el => el.closest('th').getAttribute('aria-sort')), 'descending');
  await page.reload();
  await page.locator('#resultSummary').filter({ hasText: /\d+ of \d+ players/ }).waitFor();
  assert.deepEqual(await page.locator('th [data-sort]').evaluateAll(els => els.slice(0, 4).map(el => el.dataset.sort)), ['name', 'pos', 'age', 'team']);
  await page.locator('#dbOpenFilters').click();
  const beforeDrag = await page.locator('dialog[open]').boundingBox();
  const handle = await page.locator('dialog[open] .db-dialog-head').boundingBox();
  await page.mouse.move(handle.x + 100, handle.y + 20); await page.mouse.down();
  await page.mouse.move(handle.x + 180, handle.y + 65, { steps: 10 }); await page.mouse.up();
  const afterDrag = await page.locator('dialog[open]').boundingBox();
  assert.ok(afterDrag.x > beforeDrag.x + 50); assert.ok(afterDrag.y > beforeDrag.y + 25);
  await page.locator('[data-position="SG"]').click();
  await page.locator('[data-basic="ageMax"]').fill('25');
  await page.locator('[data-add="attributes"]').click();
  await page.locator('[data-section="attributes"] [data-rule-part="value"]').fill('60');
  await page.locator('[data-add="conditions"]').click();
  await page.locator('[data-section="conditions"] [data-rule-part="value"]').fill('5');
  assert.equal(await page.locator('[data-apply]').isEnabled(), true);
  await page.screenshot({ path: path.join(os.tmpdir(), 'esl-filter-popup.png') });
  await page.locator('[data-apply]').click();
  assert.notEqual(await page.locator('#resultSummary').textContent(), summary);
  assert.equal(await page.locator('#positionFilter').inputValue(), 'SG');
  await page.locator('#dbOpenFilters').click();
  await page.locator('#dbPresetName').fill('Young shooters');
  await page.locator('[data-preset="save"]').click();
  await page.locator('[data-clear]').click();
  await page.locator('#dbPreset').selectOption({ label: 'Young shooters' });
  assert.equal(await page.locator('[data-basic="ageMax"]').inputValue(), '25');
  await page.locator('[data-apply]').click();
  await page.reload();
  await page.locator('#resultSummary').filter({ hasText: /\d+ of \d+ players/ }).waitFor();
  assert.equal(await page.locator('.db-filter-chips button').count(), 4);
  await page.locator('#dbOpenFilters').click();
  await page.locator('[data-clear]').click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal(await page.locator('.db-filter-chips button').count(), 4);
  await page.locator('#resetFilters').click();
  await page.locator('.db-filter-chips button').waitFor({ state: 'detached' });
  await page.locator('[data-sort="potential"]').click({ button: 'right' });
  await page.locator('[data-action="insert"]').click();
  await page.locator('[data-group="Potential"]').click();
  await page.screenshot({ path: path.join(os.tmpdir(), 'esl-column-menu.png') });
  await page.locator('[data-field="potentialGap"]').click();
  assert.equal(await page.locator('th [data-sort="potentialGap"]').count(), 1);
  await page.locator('#dbManageViews').click();
  await page.locator('#dbViewName').fill('Development');
  await page.locator('[data-view-action="create"]').click();
  await page.locator('#dbViewChoice').selectOption({ label: 'Development' });
  const viewDownload = page.waitForEvent('download');
  await page.locator('[data-view-action="export"]').click();
  const viewFile = await (await viewDownload).path();
  const exportedView = JSON.parse(fs.readFileSync(viewFile, 'utf8'));
  assert.equal(exportedView.view.columns.includes('potentialGap'), true);
  await page.locator('#dbImportView').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ version: 1, view: { ...exportedView.view, columns: ['name', 'unknown'], sort: 'name' } })) });
  await page.locator('#dbViewMessage').filter({ hasText: 'Unsupported fields' }).waitFor();
  await page.locator('#dbImportView').setInputFiles({ name: 'view.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...exportedView, view: { ...exportedView.view, name: 'Imported development' } })) });
  await page.locator('#dbViewMessage').filter({ hasText: 'Imported “Imported development”' }).waitFor();
  await page.locator('[data-close-views]').click();
  const csvDownload = page.waitForEvent('download');
  await page.locator('#exportCsv').click();
  const csv = fs.readFileSync(await (await csvDownload).path(), 'utf8');
  assert.equal(csv.split('\r\n').length, Number(summary.match(/of (\d+)/)[1]) + 1);
  assert.match(csv.split('\r\n')[0], /"POT","POT−OVR"/);
  await page.locator('[data-sort="potentialGap"]').click();
  await page.locator('[data-sort="potentialGap"]').click({ button: 'right' });
  await page.locator('[data-action="remove"]').click();
  assert.equal(await page.locator('th [data-sort="potentialGap"]').count(), 0);
  assert.equal(await page.locator('th').first().getAttribute('aria-sort'), 'ascending');
  await page.locator('#dbViews').selectOption({ label: 'Development' });
  await page.reload();
  await page.locator('th [data-sort="potentialGap"]').waitFor();
  assert.match(await page.locator('#dbViews').textContent(), /Development/);
  await page.locator('#seasonFilter').selectOption('career');
  await page.locator('#seasonNote').filter({ hasText: 'Career statistics' }).waitFor();
  await page.locator('#dbOpenFilters').click();
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
  await page.screenshot({ path: path.join(os.tmpdir(), 'esl-filter-dark.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(os.tmpdir(), 'esl-filter-mobile.png') });
  const fit = await page.locator('dialog[open]').evaluate(el => el.scrollWidth <= el.clientWidth + 1);
  assert.equal(fit, true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog[open]').count(), 0);
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.locator('#seasonFilter').selectOption('season-5');
  await page.waitForFunction(() => new URLSearchParams(location.search).get('season') === 'season-5');
  await page.locator('#dbOpenFilters').click();
  await page.locator('[data-basic="status"]').selectOption('potential_fa');
  await page.locator('[data-apply]').click();
  assert.match(await page.locator('.db-filter-chips').textContent(), /No contract next season/);
  // Exercise the latest-completed fallback with the same real feeds.
  await page.route('**/player-database/index.json', async route => {
    const response = await route.fetch(); const manifest = await response.json();
    manifest.currentHasStats = false; await route.fulfill({ json: manifest });
  });
  await page.goto('http://127.0.0.1:8765/00-assets/html/player-database.htm?season=current&q=');
  await page.locator('#seasonNote').filter({ hasText: 'Latest available:' }).waitFor();
  await page.locator('#resultSummary').filter({ hasText: /\d+ of \d+ players/ }).waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed:', summary, 'Screenshots:', os.tmpdir());
  await browser.close();
})().catch(err => { console.error(err); process.exit(1); });
